import { useState } from 'react'
import { useProtocolStore } from '../store/protocolStore'
import { calcSNR, calcSARLevel, calcScanTime, calcT2Blur, chemShift, identifySequence } from '../store/calculators'
import { validateProtocol } from '../utils/protocolValidator'
import type { ProtocolParams } from '../data/presets'
import { Copy, CheckCircle, FileText, Download } from 'lucide-react'

function buildExportText(params: ProtocolParams, presetLabel: string): string {
  const seqId = identifySequence(params)
  const snr = calcSNR(params)
  const sar = calcSARLevel(params)
  const time = calcScanTime(params)
  const blur = calcT2Blur(params)
  const cs = chemShift(params)
  const issues = validateProtocol(params)
  const errors = issues.filter((i) => i.severity === 'error')
  const warnings = issues.filter((i) => i.severity === 'warning')

  const fmt = (s: number) => {
    if (s < 60) return `${s}s`
    const m = Math.floor(s / 60)
    const sec = s % 60
    return sec === 0 ? `${m}min` : `${m}m${sec}s`
  }

  const fovPhase = Math.round(params.fov * (params.phaseResolution / 100))
  const voxelFreq = (params.fov / params.matrixFreq).toFixed(1)
  const voxelPhase = (fovPhase / params.matrixPhase).toFixed(1)

  const lines: string[] = [
    '═══════════════════════════════════════════════════',
    `  MRI PROTOCOL REPORT`,
    `  ${new Date().toLocaleDateString('ja-JP', { year: 'numeric', month: 'long', day: 'numeric' })}`,
    '═══════════════════════════════════════════════════',
    '',
    `Preset    : ${presetLabel || '(カスタム)'}`,
    `Sequence  : ${seqId.type}`,
    `Field     : ${params.fieldStrength}T`,
    '',
    '── Timing ─────────────────────────────────────────',
    `TR        : ${params.TR} ms`,
    `TE        : ${params.TE} ms`,
    ...(params.TI > 0 ? [`TI        : ${params.TI} ms`] : []),
    `Flip Angle: ${params.flipAngle}°`,
    `Averages  : ${params.averages}`,
    '',
    '── Sequence ────────────────────────────────────────',
    `ETL       : ${params.turboFactor}`,
    `Echo Spc  : ${params.echoSpacing} ms`,
    `Part.Four : ${params.partialFourier}`,
    ...(params.bValues.length > 1 ? [`b-values  : ${params.bValues.join(', ')} s/mm²`] : []),
    '',
    '── Resolution ──────────────────────────────────────',
    `FOV       : ${params.fov} × ${fovPhase} mm`,
    `Matrix    : ${params.matrixFreq} × ${params.matrixPhase}`,
    `Voxel     : ${voxelFreq} × ${voxelPhase} × ${params.sliceThickness} mm`,
    `Slices    : ${params.slices} × ${params.sliceThickness}mm`,
    `Bandwidth : ${params.bandwidth} Hz/px`,
    `Phase Res : ${params.phaseResolution}%`,
    '',
    '── System ──────────────────────────────────────────',
    `Coil      : ${params.coilType}`,
    `iPAT      : ${params.ipatMode === 'Off' ? 'Off' : `${params.ipatMode} ×${params.ipatFactor}`}`,
    `Gradient  : ${params.gradientMode}`,
    `Fat Sat   : ${params.fatSat}`,
    ...(params.mt ? ['MT        : On'] : []),
    '',
    '── Geometry ────────────────────────────────────────',
    `Orient    : ${params.orientation}`,
    `Phase Dir : ${params.phaseEncDir}`,
    `Phase Ovs : ${params.phaseOversampling}%`,
    ...(params.satBands ? ['Sat Bands : On'] : []),
    '',
    '── Physio ──────────────────────────────────────────',
    `ECG Trig  : ${params.ecgTrigger ? `On (Delay: ${params.triggerDelay}ms)` : 'Off'}`,
    `Resp.Ctrl : ${params.respTrigger}`,
    '',
    '── Calculated Metrics ──────────────────────────────',
    `Scan Time : ${fmt(time)}`,
    `SNR (rel) : ${snr}`,
    `SAR       : ${sar}% of limit`,
    `T2 Blur   : ${blur.toFixed(2)} (1.0=sharp)`,
    `Chem.Shift: ${cs} px`,
    '',
    ...(errors.length > 0 ? [
      '── ERRORS ──────────────────────────────────────────',
      ...errors.map(e => `  ✕ [${e.id}] ${e.title}`),
      '',
    ] : []),
    ...(warnings.length > 0 ? [
      '── WARNINGS ────────────────────────────────────────',
      ...warnings.map(w => `  ⚠ [${w.id}] ${w.title}`),
      '',
    ] : []),
    ...(errors.length === 0 && warnings.length === 0 ? ['  ✓ Protocol validation passed\n'] : []),
    '═══════════════════════════════════════════════════',
    '  Generated by MRI Protocol Simulator (syngo-style)',
    '═══════════════════════════════════════════════════',
  ]

  return lines.join('\n')
}

function buildJsonExport(params: ProtocolParams, presetLabel: string): string {
  const seqId = identifySequence(params)
  const fovPhase = Math.round(params.fov * (params.phaseResolution / 100))
  const voxelFreq = parseFloat((params.fov / params.matrixFreq).toFixed(2))
  const voxelPhase = parseFloat((fovPhase / params.matrixPhase).toFixed(2))
  const obj = {
    meta: {
      preset: presetLabel || '(カスタム)',
      sequence: seqId.type,
      exportedAt: new Date().toISOString(),
      generator: 'MRI Protocol Simulator',
    },
    routine: {
      TR: params.TR, TE: params.TE, TI: params.TI, flipAngle: params.flipAngle,
      slices: params.slices, sliceThickness: params.sliceThickness, sliceGap: params.sliceGap,
      averages: params.averages,
    },
    sequence: {
      turboFactor: params.turboFactor, echoSpacing: params.echoSpacing,
      partialFourier: params.partialFourier, bValues: params.bValues,
    },
    resolution: {
      fov: params.fov, fovPhase, matrixFreq: params.matrixFreq, matrixPhase: params.matrixPhase,
      voxelFreq, voxelPhase, voxelSlice: params.sliceThickness,
      phaseResolution: params.phaseResolution, bandwidth: params.bandwidth, interpolation: params.interpolation,
    },
    contrast: { fatSat: params.fatSat, mt: params.mt },
    geometry: { orientation: params.orientation, phaseEncDir: params.phaseEncDir, satBands: params.satBands },
    system: {
      fieldStrength: params.fieldStrength, coilType: params.coilType,
      ipatMode: params.ipatMode, ipatFactor: params.ipatFactor,
      gradientMode: params.gradientMode, shim: params.shim,
    },
    physio: {
      ecgTrigger: params.ecgTrigger, respTrigger: params.respTrigger,
      triggerDelay: params.triggerDelay, triggerWindow: params.triggerWindow,
    },
    inline: {
      adc: params.inlineADC, mip: params.inlineMIP, mpr: params.inlineMPR, subtraction: params.inlineSubtraction,
    },
    metrics: {
      snrRel: calcSNR(params),
      sarPct: calcSARLevel(params),
      scanTimeSec: calcScanTime(params),
      t2blur: parseFloat(calcT2Blur(params).toFixed(3)),
      chemShiftPx: chemShift(params),
    },
  }
  return JSON.stringify(obj, null, 2)
}

export function ProtocolExportPanel() {
  const { params, activePresetId } = useProtocolStore()
  const [copied, setCopied] = useState(false)
  const [format, setFormat] = useState<'text' | 'csv' | 'json'>('text')

  // Find preset label
  const presetLabel = activePresetId ?? ''

  const exportText = buildExportText(params, presetLabel)
  const jsonExport = buildJsonExport(params, presetLabel)

  const csvLines = [
    'Parameter,Value,Unit',
    `TR,${params.TR},ms`,
    `TE,${params.TE},ms`,
    `TI,${params.TI},ms`,
    `FlipAngle,${params.flipAngle},deg`,
    `ETL,${params.turboFactor},`,
    `EchoSpacing,${params.echoSpacing},ms`,
    `FOV,${params.fov},mm`,
    `FOVPhase,${Math.round(params.fov * params.phaseResolution / 100)},mm`,
    `MatrixFreq,${params.matrixFreq},`,
    `MatrixPhase,${params.matrixPhase},`,
    `SliceThickness,${params.sliceThickness},mm`,
    `Slices,${params.slices},`,
    `Bandwidth,${params.bandwidth},Hz/px`,
    `Averages,${params.averages},`,
    `PartialFourier,${params.partialFourier},`,
    `iPATMode,${params.ipatMode},`,
    `iPATFactor,${params.ipatFactor},`,
    `FatSat,${params.fatSat},`,
    `FieldStrength,${params.fieldStrength},T`,
    `Coil,${params.coilType},`,
    `ECGTrigger,${params.ecgTrigger ? 'On' : 'Off'},`,
    `TriggerDelay,${params.triggerDelay},ms`,
    `RespControl,${params.respTrigger},`,
    `SNR,${calcSNR(params)},rel`,
    `SAR,${calcSARLevel(params)},%`,
    `ScanTime,${calcScanTime(params)},s`,
  ].join('\n')

  const getContent = () => {
    if (format === 'text') return exportText
    if (format === 'csv') return csvLines
    return jsonExport
  }

  const handleCopy = () => {
    navigator.clipboard.writeText(getContent()).then(() => {
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    }).catch(() => {})
  }

  const handleDownload = () => {
    const ext = format === 'csv' ? 'csv' : format === 'json' ? 'json' : 'txt'
    const mime = format === 'csv' ? 'text/csv' : format === 'json' ? 'application/json' : 'text/plain'
    const blob = new Blob([getContent()], { type: mime })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    const presetSlug = (activePresetId ?? 'custom').replace(/[^a-z0-9]/gi, '_')
    a.href = url
    a.download = `mri_protocol_${presetSlug}.${ext}`
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <div className="h-full flex flex-col overflow-hidden" style={{ background: '#0a0a0a', color: '#c8ccd6' }}>
      {/* Header */}
      <div className="px-3 py-2 shrink-0" style={{ background: '#111', borderBottom: '1px solid #252525' }}>
        <div className="flex items-center gap-1.5 mb-0.5">
          <FileText size={11} style={{ color: '#60a5fa' }} />
          <span className="font-semibold" style={{ color: '#60a5fa', fontSize: '11px' }}>Protocol Export</span>
        </div>
        <div style={{ color: '#4b5563', fontSize: '9px' }}>プロトコルをテキストまたはCSVでエクスポート</div>
      </div>

      {/* Format selector */}
      <div className="px-3 py-2 shrink-0 flex items-center gap-2" style={{ borderBottom: '1px solid #1a1a1a' }}>
        <div className="flex gap-1">
          {(['text', 'csv', 'json'] as const).map(f => (
            <button
              key={f}
              onClick={() => setFormat(f)}
              className="px-2 py-0.5 rounded text-xs transition-colors"
              style={{
                background: format === f ? '#0d1520' : 'transparent',
                color: format === f ? '#60a5fa' : '#4b5563',
                border: `1px solid ${format === f ? '#1d4ed8' : '#252525'}`,
                fontSize: '9px',
              }}
            >
              {f.toUpperCase()}
            </button>
          ))}
        </div>
        <div className="ml-auto flex gap-1">
          <button
            onClick={handleDownload}
            className="flex items-center gap-1 px-2 py-0.5 rounded transition-colors"
            style={{
              background: '#1a1a1a',
              color: '#9ca3af',
              border: '1px solid #252525',
              fontSize: '9px',
              fontWeight: 600,
            }}
          >
            <Download size={10} />
            DL
          </button>
          <button
            onClick={handleCopy}
            className="flex items-center gap-1 px-2 py-0.5 rounded transition-colors"
            style={{
              background: copied ? '#0d2010' : '#1a1a1a',
              color: copied ? '#4ade80' : '#60a5fa',
              border: `1px solid ${copied ? '#166534' : '#1d4ed8'}`,
              fontSize: '9px',
              fontWeight: 600,
            }}
          >
            {copied ? <CheckCircle size={10} /> : <Copy size={10} />}
            {copied ? '完了' : 'コピー'}
          </button>
        </div>
      </div>

      {/* Preview */}
      <div className="flex-1 overflow-y-auto p-3">
        <pre
          className="text-xs rounded p-3 overflow-x-auto"
          style={{
            background: '#080808',
            border: '1px solid #1a1a1a',
            color: '#9ca3af',
            fontFamily: 'monospace',
            fontSize: '9px',
            lineHeight: '1.6',
            whiteSpace: 'pre',
          }}
        >
          {getContent()}
        </pre>
      </div>
    </div>
  )
}
